// THIS FILE IS AUTO-GENERATED BY update_assets.sh!

use crate::add_asset;

pub fn load_dynamic_assets() {


add_asset(
        &["/assets/hooks.module-1a3b3e2f.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/hooks.module-1a3b3e2f.js.gz").to_vec(),
    );
add_asset(
        &["/assets/http-d7aff5a7.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/http-d7aff5a7.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-5d0f1922.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-5d0f1922.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-84a5a395.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-84a5a395.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-89f592b8.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-89f592b8.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-983f8499.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-983f8499.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-a23a08c8.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-a23a08c8.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index.es-93a294c8.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index.es-93a294c8.js.gz").to_vec(),
    );
add_asset(
        &["/assets/tslib-da697055.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/tslib-da697055.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-fbdd9b61.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-fbdd9b61.css.gz").to_vec(),
    );
add_asset(
        &["/assets/index-fbdd9b61.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-fbdd9b61.css.gz").to_vec(),
    );

}
