// THIS FILE IS AUTO-GENERATED BY update_assets.sh!

use crate::add_asset;

pub fn load_dynamic_assets() {


add_asset(
        &["/assets/ccip-Q6_riycM.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/ccip-Q6_riycM.js.gz").to_vec(),
    );
add_asset(
        &["/assets/hooks.module-BP10CNNA.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/hooks.module-BP10CNNA.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-Bc1u-EQ9.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-Bc1u-EQ9.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-BqtktcFn.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-BqtktcFn.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-BrYTjowf.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-BrYTjowf.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-C86YS_34.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-C86YS_34.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-CFMGMsN-.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-CFMGMsN-.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-CHDM0Z6X.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-CHDM0Z6X.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-SMHtEk9t.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-SMHtEk9t.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index.es-C-mGk9SR.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index.es-C-mGk9SR.js.gz").to_vec(),
    );
add_asset(
        &["/assets/secp256k1-BKcE3JXf.js"],
        vec![
            ("Content-Type".to_string(), "text/javascript".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/secp256k1-BKcE3JXf.js.gz").to_vec(),
    );
add_asset(
        &["/assets/index-DheiDXl9.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-DheiDXl9.css.gz").to_vec(),
    );
add_asset(
        &["/assets/index-DheiDXl9.css"],
        vec![
            ("Content-Type".to_string(), "text/css".to_string()),
            ("Content-Encoding".to_string(), "gzip".to_string()),
            ("Cache-Control".to_string(), "public".to_string()),
        ],
        include_bytes!("../../build/assets/index-DheiDXl9.css.gz").to_vec(),
    );

}
